apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    type: compute-self-service
  name: fernando
  namespace: self-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fernando
      type: compute-self-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fernando
        type: compute-self-service
    spec:
      containers:
      - args:
        - cat
        image: fernandorejonbarrera/dev-storage:0.1.3
        imagePullPolicy: IfNotPresent
        name: main
        resources:
          requests:
            cpu: 1700m
            memory: 15300Mi
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /root
          name: home-data
        - mountPath: /var/lib/docker
          name: docker-data
      nodeSelector:
        op: self-service-fast
      restartPolicy: Always
      securityContext: {}
      tolerations:
      - effect: NoSchedule
        key: op
        operator: Equal
        value: self-service
      volumes:
      - name: home-data
        persistentVolumeClaim:
          claimName: fernando
      - name: docker-data
        persistentVolumeClaim:
          claimName: fernando-docker
---
apiVersion: v1
kind: Service
metadata:
  labels:
    type: compute-self-service
  name: fernando
  namespace: self-service
spec:
  ports:
  - port: 22
    name: ssh
    protocol: TCP
    targetPort: 22
  - port: 2375
    name: docker
    protocol: TCP
  selector:
    app: fernando
    type: compute-self-service
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    type: compute-self-service
  name: fernando
  namespace: self-service
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: hot
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    type: compute-self-service
  name: fernando-docker
  namespace: self-service
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 123Gi
  storageClassName: hot
  volumeMode: Filesystem